### ISSUE TITLE
Sisfall Enhanced Dataset contains all 0s

### ISSUE THREAD

**Issue by jing-yu-lim** [mojtabaSefidi/Fall-Detection-System#2]
Hello, 

May I kindly check on the Sisfall Enhanced dataset with labels? After downloading using the command, I unzipped the file using 'unzip' and it turns out that all the txt files contains all 0s.

Thank you

**Comment by mojtabaSefidi** [comment]
Hi, Thanks for reaching out.

In each activity, `[SA01 to SA23]` and `[SE01-SE15]`, we have two types of trials. **The falls don't occur** in the ones that start with the letter `D`, like `D01_SA17_R01.txt`. **So, all of the labels are 0 for these types of trials**. On the other hand, **the fall occurs** in other trials whose name starts with the letter `F` like `F01_SA17_R01.txt`. In these trials, **there is a moment when the labels **turn from 0 to 1**, which shows the participant **is about to fall** in that moment**. 

<img width="45" alt="Screenshot 2024-11-08 at 17 18 49" src="https://github.com/user-attachments/assets/6fa6be41-88a1-4e24-a8a2-3d98badb9309">


**After that, when labels turn from 1 to 2, the participant ultimately falls.**

<img width="25" alt="Screenshot 2024-11-08 at 17 21 48" src="https://github.com/user-attachments/assets/666953af-bfb1-4e1d-b5d8-a6afc5a26219">
